// Implementation file for parser generated by fsyacc
module RegexGrammar
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "src/RegexGrammar.fsy"

open RegexAST

# 10 "src/RegexGrammar.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | CHAR of (char)
  | LPAREN
  | RPAREN
  | STAR
  | PLUS
  | PIPE
  | EOF
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_CHAR
    | TOKEN_LPAREN
    | TOKEN_RPAREN
    | TOKEN_STAR
    | TOKEN_PLUS
    | TOKEN_PIPE
    | TOKEN_EOF
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startregex
    | NONTERM_regex
    | NONTERM_expr
    | NONTERM_term
    | NONTERM_factor
    | NONTERM_atom

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | CHAR _ -> 0 
  | LPAREN  -> 1 
  | RPAREN  -> 2 
  | STAR  -> 3 
  | PLUS  -> 4 
  | PIPE  -> 5 
  | EOF  -> 6 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_CHAR 
  | 1 -> TOKEN_LPAREN 
  | 2 -> TOKEN_RPAREN 
  | 3 -> TOKEN_STAR 
  | 4 -> TOKEN_PLUS 
  | 5 -> TOKEN_PIPE 
  | 6 -> TOKEN_EOF 
  | 9 -> TOKEN_end_of_input
  | 7 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startregex 
    | 1 -> NONTERM_regex 
    | 2 -> NONTERM_expr 
    | 3 -> NONTERM_expr 
    | 4 -> NONTERM_term 
    | 5 -> NONTERM_term 
    | 6 -> NONTERM_factor 
    | 7 -> NONTERM_factor 
    | 8 -> NONTERM_factor 
    | 9 -> NONTERM_atom 
    | 10 -> NONTERM_atom 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 9 
let _fsyacc_tagOfErrorTerminal = 7

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | CHAR _ -> "CHAR" 
  | LPAREN  -> "LPAREN" 
  | RPAREN  -> "RPAREN" 
  | STAR  -> "STAR" 
  | PLUS  -> "PLUS" 
  | PIPE  -> "PIPE" 
  | EOF  -> "EOF" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | CHAR _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | LPAREN  -> (null : System.Object) 
  | RPAREN  -> (null : System.Object) 
  | STAR  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | PIPE  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us;65535us;1us;65535us;0us;1us;2us;65535us;0us;2us;14us;5us;3us;65535us;0us;4us;6us;7us;14us;4us;5us;65535us;0us;8us;4us;9us;6us;8us;7us;9us;14us;8us;5us;65535us;0us;10us;4us;10us;6us;10us;7us;10us;14us;10us;|]
let _fsyacc_sparseGotoTableRowOffsets = [|0us;1us;3us;6us;10us;16us;|]
let _fsyacc_stateToProdIdxsTableElements = [| 1us;0us;1us;0us;2us;1us;3us;1us;1us;2us;2us;5us;2us;3us;10us;1us;3us;2us;3us;5us;1us;4us;1us;5us;3us;6us;7us;8us;1us;7us;1us;8us;1us;9us;1us;10us;1us;10us;|]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us;2us;4us;7us;9us;12us;15us;17us;20us;22us;24us;28us;30us;32us;34us;36us;|]
let _fsyacc_action_rows = 16
let _fsyacc_actionTableElements = [|2us;32768us;0us;13us;1us;14us;0us;49152us;2us;32768us;5us;6us;6us;3us;0us;16385us;2us;16386us;0us;13us;1us;14us;2us;32768us;2us;15us;5us;6us;2us;32768us;0us;13us;1us;14us;2us;16387us;0us;13us;1us;14us;0us;16388us;0us;16389us;2us;16390us;3us;11us;4us;12us;0us;16391us;0us;16392us;0us;16393us;2us;32768us;0us;13us;1us;14us;0us;16394us;|]
let _fsyacc_actionTableRowOffsets = [|0us;3us;4us;7us;8us;11us;14us;17us;20us;21us;22us;25us;26us;27us;28us;31us;|]
let _fsyacc_reductionSymbolCounts = [|1us;2us;1us;3us;1us;2us;1us;2us;2us;1us;3us;|]
let _fsyacc_productionToNonTerminalTable = [|0us;1us;2us;2us;3us;3us;4us;4us;4us;5us;5us;|]
let _fsyacc_immediateActions = [|65535us;49152us;65535us;16385us;65535us;65535us;65535us;65535us;16388us;16389us;65535us;16391us;16392us;16393us;65535us;16394us;|]
let _fsyacc_reductions = lazy [|
# 116 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> RegexAST.regex in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startregex));
# 125 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 11 "src/RegexGrammar.fsy"
                                       _1 
                   )
# 11 "src/RegexGrammar.fsy"
                 : RegexAST.regex));
# 136 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_term in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 13 "src/RegexGrammar.fsy"
                                  _1 
                   )
# 13 "src/RegexGrammar.fsy"
                 : 'gentype_expr));
# 147 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_term in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 14 "src/RegexGrammar.fsy"
                                            Alt(_1, _3) 
                   )
# 14 "src/RegexGrammar.fsy"
                 : 'gentype_expr));
# 159 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_factor in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 16 "src/RegexGrammar.fsy"
                                    _1 
                   )
# 16 "src/RegexGrammar.fsy"
                 : 'gentype_term));
# 170 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_term in
            let _2 = parseState.GetInput(2) :?> 'gentype_factor in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 17 "src/RegexGrammar.fsy"
                                         Concat(_1, _2) 
                   )
# 17 "src/RegexGrammar.fsy"
                 : 'gentype_term));
# 182 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_atom in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 19 "src/RegexGrammar.fsy"
                                    _1 
                   )
# 19 "src/RegexGrammar.fsy"
                 : 'gentype_factor));
# 193 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_atom in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "src/RegexGrammar.fsy"
                                         Star _1 
                   )
# 20 "src/RegexGrammar.fsy"
                 : 'gentype_factor));
# 204 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_atom in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 21 "src/RegexGrammar.fsy"
                                         Plus _1 
                   )
# 21 "src/RegexGrammar.fsy"
                 : 'gentype_factor));
# 215 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> char in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "src/RegexGrammar.fsy"
                                  Char _1 
                   )
# 23 "src/RegexGrammar.fsy"
                 : 'gentype_atom));
# 226 "src/RegexGrammar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 24 "src/RegexGrammar.fsy"
                                                _2 
                   )
# 24 "src/RegexGrammar.fsy"
                 : 'gentype_atom));
|]
# 238 "src/RegexGrammar.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions = _fsyacc_reductions.Value;
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 10;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let regex lexer lexbuf : RegexAST.regex =
    engine lexer lexbuf 0 :?> _
